# docs/_config.yml
title: Seeking His Kingdom
baseurl: ""   # Change this to "/SHK" when testing and "" to deploy
url: https://www.seekinghiskingdom.org
permalink: pretty
timezone: America/Chicago
source: docs
permalink: pretty

# Keep non-site stuff out of the build
exclude:
  - scripts/
  - qa/
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock